DROP TABLE IF EXISTS SOCIAL_NETWORK_POST;
CREATE TABLE SOCIAL_NETWORK_POST (
 POST_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
 AUTHOR_NAME VARCHAR(50) NOT NULL,
 POST_CONTENT VARCHAR(MAX) NOT NULL,
 POST_DATE DATE,
 VIEW_COUNT int NOT NULL
);
